### ISSUE TITLE
The link to the Pre-trained models is broken

### ISSUE THREAD

**Issue by practicStar** [james-oldfield/PandA#3]
I cannot download the model through this link "wget -r -np -nH --cut-dirs=2 -R *index* http://eecs.qmul.ac.uk/~jo001/PandA-pretrained-models/"

**Comment by james-oldfield** [comment]
Hi!

Thanks for spotting this! I've now fixed the link. Is the link now working again for you (perhaps on a private browser or after clearing the cache)?

Thanks!

**Comment by practicStar** [comment]
> Hi!
> 
> Thanks for spotting this! I've now fixed the link. Is the link now working again for you (perhaps on a private browser or after clearing the cache)?
> 
> Thanks!

The link is now working. Thank you so much for fixing it!
